version: "3.9"
services:
  fastapi:
    build: .
    container_name: fastapi
    restart: always
    expose:
      - "8000"  # 외부 포트는 Nginx가 사용
    volumes:
      - ./patch_files:/app/patches
      - ./patch_files/version.json:/app/patches/version.json
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"   # LAN에서 접근할 포트
    volumes:
      - ./patch_files:/app/patches
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge